name: 'gh-release'

on:
  push:
    branches:
      - 'main'

jobs:
  pre-release:
    name: 'Pre Release'
    runs-on: 'self-hosted'

    steps:
      - name: 'Build & test'
        run: |
          echo 'done!'

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: false
          title: 'Development Build'
